const GAME_STATE = {
    PRE_START :"PRESTART",
    PREPARE : "PREPARE",
    ROUND_DECISION :"ROUNDDECISION",
    ROUND_ACTION :"ROUNDACTION",
    MATCH :"MATCH",
    SWISH_CALLED :"SWISHCALLED",
    SWISH_END:"SWISHEND",
   }



   module.exports = {GAME_STATE}